clinvar_release: 20230730
cosmic_min_freq: 0.001

window_size: 128
center_window_size: 100

per_device_batch_size: 2048
dataloader_num_workers: 32

gnomad:
  min_an: 25_000
  subsample: 500_000
  consequences:
    - missense
    - synonymous
    - 5_prime_UTR
    - 3_prime_UTR
    - upstream_gene
    - downstream_gene
    - intron
    - intergenic
    - non_coding_transcript_exon
  enformer_consequences:
    - upstream_gene
    - intergenic
    - downstream_gene
    - intron